# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS (Matt Middleton)">
# Copyright (c) Meridian Technology Consulting Services (Matt Middleton).
# All rights reserved.
# </copyright>
# -----------------------------------------------------------------------------

# Configuration
configuration: release

# Before Build Config
before_build:
  - nuget restore Meridian.InterSproc\Meridian.InterSproc.sln

# Build Config
build:
  project: Meridian.InterSproc\Meridian.InterSproc.sln

# After Build Config
after_build:
- cmd: |
    7z a Meridian.InterSproc.%appveyor_build_version%.zip %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\*.*
    AppVeyor PushArtifact Meridian.InterSproc.%appveyor_build_version%.zip -DeploymentName "Meridian.InterSproc Binaries"
    nuget pack %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\Meridian.InterSproc.csproj

# Artifact Config
artifacts:
  - path: "*.nupkg"
    name: Meridian.InterSproc.NuGet
      
# Deployment Config
deploy:
  provider: NuGet
  api_key:
    secure: i9i5jzcTiE6pl5ybDzeewAQBATNszjZwj4yxYeYlwUjmVDnt0obGATs86GoedqLT