# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS (Matt Middleton)">
# Copyright (c) Meridian Technology Consulting Services (Matt Middleton).
# All rights reserved.
# </copyright>
# -----------------------------------------------------------------------------

# Before Build Config
before_build:
  - nuget restore Meridian.InterSproc\Meridian.InterSproc.sln

# Deployment Config
deploy:
  provider: NuGet
  api_key:
    secure: i9i5jzcTiE6pl5ybDzeewAQBATNszjZwj4yxYeYlwUjmVDnt0obGATs86GoedqLT