# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS (Matt Middleton)">
# Copyright (c) Meridian Technology Consulting Services (Matt Middleton).
# All rights reserved.
# </copyright>
# -----------------------------------------------------------------------------

# Configuration
configuration: release

# Only master branch
branches:
  only:
  - master

# Build script
build_script:
- cmd: |
    dotnet publish Meridian.InterSproc\Meridian.InterSproc\Meridian.InterSproc.csproj --output %APPVEYOR_BUILD_FOLDER%
    copy %APPVEYOR_BUILD_FOLDER%\LICENSE.md %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\netstandard2.0\Meridian.InterSproc-LICENSE.txt
    xcopy /s %APPVEYOR_BUILD_FOLDER%\Licenses %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\netstandard2.0\
    7z a Meridian.InterSproc.zip %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\netstandard2.0\*.*
    dotnet pack Meridian.InterSproc\Meridian.InterSproc\Meridian.InterSproc.csproj --output %APPVEYOR_BUILD_FOLDER%

# Artifact Config
artifacts:
  - path: "*.nupkg"
    name: Meridian.InterSproc NuGet Package
  - path: Meridian.InterSproc.zip
    name: "Meridian.InterSproc Binaries"
      
# Deployment Config
deploy:
  provider: NuGet
  api_key:
    secure: i9i5jzcTiE6pl5ybDzeewAQBATNszjZwj4yxYeYlwUjmVDnt0obGATs86GoedqLT