# -----------------------------------------------------------------------------
# <copyright file="appveyor.yml" company="MTCS (Matt Middleton)">
# Copyright (c) Meridian Technology Consulting Services (Matt Middleton).
# All rights reserved.
# </copyright>
# -----------------------------------------------------------------------------

# Configuration
configuration: release

# Only master branch
branches:
  only:
  - master

# Build script
build_script:
- cmd: |
    dotnet publish Meridian.InterSproc\Meridian.InterSproc\Meridian.InterSproc.csproj --output %appveyor_build_folder%
    copy %APPVEYOR_BUILD_FOLDER%\LICENCE.md %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc-LICENCE.txt
    xcopy /s %APPVEYOR_BUILD_FOLDER%\Licences %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\
    7z a Meridian.InterSproc.zip %APPVEYOR_BUILD_FOLDER%\Meridian.InterSproc\Meridian.InterSproc\bin\Release\netstandard2.0\*.*
    AppVeyor PushArtifact Meridian.InterSproc.zip -DeploymentName "Meridian.InterSproc Binaries"

# Artifact Config
artifacts:
  - path: "*.nupkg"
    name: Meridian.InterSproc NuGet Pacakge
      
# Deployment Config
deploy:
  provider: NuGet
  api_key:
    secure: i9i5jzcTiE6pl5ybDzeewAQBATNszjZwj4yxYeYlwUjmVDnt0obGATs86GoedqLT